name: generate animation

on:
  # chạy tự động mỗi 24 giờ
  schedule:
    - cron: "0 */24 * * *" 
  
  # cho phép chạy công việc thủ công bất kỳ lúc nào
  workflow_dispatch:
  
  # chạy mỗi khi có push trên nhánh master
  push:
    branches:
    - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # tạo game con rắn từ biểu đồ đóng góp của người dùng GitHub (<github_user_name>), đầu ra là một ảnh svg động tại <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: trunglienquy  # Thay đổi thành tên GitHub của bạn
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # đẩy nội dung của <build_dir> lên nhánh output
      # nội dung sẽ có sẵn tại https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file>, hoặc như một trang GitHub
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
